### ISSUE TITLE
retconTransform not working

### ISSUE THREAD

**Issue by elivnjak** [mmikkel/RetconHTML-Craft#1]
I'm trying to resize images inserted into the body. I've tried most of the methods listed but it doesnt seem to change the image url at all. My final attempt was to try to get the inline but again no luck.

```
{{ entry.body | retconTransform( { width : 1024, height : 768, mode : 'fit' } ) }}
```

**Comment by mmikkel** [comment]
Hello @elivnjak,

A few of things to check, right off the bat:
1. Retcon will only transform _local_ assets, for now. If the original image is not found on the local server, Retcon will return the original URL
2. By default, Retcon will store your transformed image under _[your public root]/[path to original file]/[name_of_transform]/_. Whatever user your process is running as (e.g. _www-data_) needs to be able to both create and write to this directory. Note that you can always set a totally different base directory for Retcon to store its transformed images in – see plugin settings.
3. Check your log files – both Craft's and Apache/Nginx's – you might find a clue there.

If your asset is local and the original URL is still returned, that would mean Retcon was unable to successfully transform and/or store the image. This could be due to a number of issues (named transform doesn't exist, the relevant folders aren't writable, the HTML is malformed in some way, etc).

There are cases where Retcon will throw errors, but I've been cautious about adding too many breakpoints. Seeing as HTML manipulation can be a rather finicky effort and the input can basically be _anything_, if Retcon is unable to do its task successfully, its in my opinion usually better to return the original content than to choke the entire site with a PHP error.

Note: I'm currently working on adding error logging for Retcon, as well as some debugging options – both of which should make it easier to track down the cause of any issues with the output.

**Comment by mmikkel** [comment]
Also – could you put your entire `entry.body` HTML output in a Gist? I'd be happy to look it over quickly and see if I can spot any obvious problems (remove any Retcon filters beforehand).

**Comment by mmikkel** [comment]
Hello again, @elivnjak – I stumbled across a couple of bugs related to image transforms just now (see https://github.com/mmikkel/RetconHTML-Craft/issues/3 and https://github.com/mmikkel/RetconHTML-Craft/issues/2), and have pushed an update (1.0.1). Could you try updating the plugin and see if your issue is resolved?

**Comment by elivnjak** [comment]
Hi @mmikkel 

I've updated to the latest version but still not having any luck. 

```
<p><img src="//mydomain.com/assets/images/heroBanners/desktop/banner-01.jpg" class="img-content"><br></p>
```

The logs dont appear to have anything regarding it either. One issue i also had was:

```
Use of undefined constant CRAFT_SITE_URL - assumed 'CRAFT_SITE_URL'
/home/elivnjak/craft/plugins/retconhtml/services/RetconHtml_HelperService.php(32)
32             $settings[ 'baseTransformUrl' ] = trim( rtrim( $pluginSettings->baseTransformUrl, '/' ) ?: rtrim( CRAFT_SITE_URL, '/' ) );
```

Not sure if its related..

**Comment by mmikkel** [comment]
Thanks alot for following up, @elivnjak – really appreciate it.

In regards to that specific error message, I couldn't say whether this issue is the root cause of your transforms not working or not, but that error will definitely stop Retcon dead in its tracks – so good catch! **The bug is amended in [version 1.0.2](https://github.com/mmikkel/RetconHTML-Craft/archive/master.zip). Again, would really appreciate it if you could check it out and get back to me.**

To explain a little bit about what's happening here: Before attempting a transform, Retcon first checks if your asset is local or not. It looks at your site's URL to do this, which is where the constant `CRAFT_SITE_URL` comes in. I wrongly assumed that even if you don't define this constant yourself in the config files, Craft would define it for you. Turns out that my assumption is wrong and the constant could very well be undefined – ouch.

If you're interested, you can read more about CRAFT_SITE_URL and other optional/user defined constants [here](http://buildwithcraft.com/docs/php-constants#craft-site-url). Its main use is in relation to multienvironment configurations.
