### ISSUE TITLE
Add ability to use transforms set in the template?

### ISSUE THREAD

**Issue by katrinkerber** [mmikkel/RetconHTML-Craft#6]
Thank you very much for your plugin - I've managed to optimise a site for a client who uploads mahooooosive images via Redactor.

I prefer [setting my transforms in the template](http://buildwithcraft.com/docs/image-transforms#defining-transforms-in-your-templates), but realised the plugin doesn't pick up on those.

I know there is the option of inline transforms, but that's not very DRY when dealing with multiple Redactor fields on a template.

Maybe this could be added?

**Comment by mmikkel** [comment]
Hello @katrinkerber – thanks a lot for the kind words, very fun to hear that Retcon was useful to you!

An "inline transform" is any transform that is declared in the template (as opposed to a "named transform", which is defined in the Craft CP). It's impossible to "pick up on" inline transforms, because they only exist in the runtime – there isn't any related data stored in the database.

However, you can cast the inline transform to a variable, and re-use that variable throughout your template, instead of declaring the same transform multiple times. This works well with Retcon. An example:

``` jinja
{% set myTransform = { width : 1024, height : 768 } %}
```

``` html
<p class="excerpt">{{ entry.excerpt | retconTransform(myTransform) }}</p>
<section class="copy">{{ entry.body | retconTransform(myTransform) }}</p>
```

Hope this helps you out! I'll close this issue as there isn't really anything to add to the plugin, but I'll be updating the docs to include the example above :)

**Comment by katrinkerber** [comment]
Setting a variable - of course! Doh! Sometimes the easiest solutions are the hardest to think of. Thank you :)
