### ISSUE TITLE
URL issue possibly caused by fixSlashes?

### ISSUE THREAD

**Issue by mrnebbi** [mmikkel/RetconHTML-Craft#9]
Hi there,

I'm getting an issue in that if I set the Base transform URL to `/` then my images URLs end up missing a / after http:/. I tried tracking down the problem I get the following:

Line 268 `$imageTransformedUrl = $this->fixSlashes(str_replace($basePath, ($useAbsoluteUrl ? $baseUrl : ''), $imageTransformedPath));`

`$imageTransformedUrl` returns http:/www.domainname.com/uploads/_transformName/image.jpg
without `fixSlashes` it returns http://www.domainname.com/uploads/_transformName/image.jpg

If I change the Base Transform URL to `{uploadsUrl}/` I get double folder names, as well as the fixSlashes problem.

`$imageTransformedUrl` returns http:/www.domainname.com/uploads/uploads/_transformName/image.jpg
without `fixSlashes` it returns http://www.domainname.com/uploads/uploads/_transformName/image.jpg

My `uploadsUrl` variable is set to `'uploadsUrl' => 'http://www.domainname.com/uploads'`

**Comment by mmikkel** [comment]
Yeah, that's a bug. Sorry for not catching this sooner, I've been heaps busy later. For a quickfix (I know it's ugly) you could do something like this:

`{{ entry.body|retconTransform('sometransform')|replace('http:/www', 'http://www') }}`

I'll get it sorted ASAP, though.

**Comment by mmikkel** [comment]
Hello @ianisted – `fixSlashes` no longer strips double slashes from protocols (i.e. `http://`) in [release 1.3.2](https://github.com/mmikkel/RetconHTML-Craft/releases/tag/v1.3.2).

Be advised that the `baseTransformUrl` setting is still relative to the whatever URL the asset originally returns (which is why you'll get paths like `/uploads/uploads/` if you use the absolute URL for that setting. This is by design and I'm not going to change this due to backwards compatibility (also I kind of consider it a non-issue until I'm convinced otherwise; just use `/` or the base site URL to your site for the `baseTransformUrl` setting. 

Thanks for contributing!

**Comment by mrnebbi** [comment]
Hi @mmikkel, thanks for the update. Absolutely appreciate you can't work on this 24/7. Thanks for taking the time provide a fix, and for releasing such a useful plugin!
